backend:
  name: git-gateway
  branch: main
  identity_url: https://dxc.netlify.app/.netlify/identity

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "text" }