name: git-geteway
branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Project Title", name: "title", widget: "string" }

      - { label: "Description", name: "description", widget: "text" }

      - { label: "Project Image", name: "image", widget: "image" }

      - { label: "Project Link", name: "link", widget: "string" }